name = "fedora-blueprint"
description = "fedora blueprint including k8s and containerd packages"
version = "0.0.1"
distro = "fedora-38"

[[packages]]
name = "kubelet"
version = "*"

[[packages]]
name = "kubeadm"
version = "*"

[[packages]]
name = "kubectl"
version = "*"

[[packages]]
name = "containerd"
version = "*"