---

- hosts: all
  remote_user: liveuser
  gather_facts: true
  roles:  
  - role: deploy_k8s
  - role: deploy_console
    when: k8s_console_deployment|bool == true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
